### ISSUE TITLE
Jinja support

### ISSUE THREAD

**Issue by Kokiro** [bprinty/Flask-Authorize#19]
Hi, it looks great, exactly what I was looking for.

Do you plan to support Jinja?

**Comment by bprinty** [comment]
Can you give an example of how you'd like to use it with Jinja? That'll help me figure out what needs to happen to add support. Thanks!

**Comment by Kokiro** [comment]
Hi, please have a look at this link, it is exactly what I need:
https://github.com/Kozea/flask-alcool#display-links-only-for-authorized-routes

Here if the decorator "fails" the block is not visible.

**Comment by bprinty** [comment]
Sweet, thanks! I’ll take a look and let you know when I have a PR for the functionality.

**Comment by bprinty** [comment]
I added this issue to the 0.1.4 milestone - feel free to suggest more features that we can include in that release.

**Comment by bprinty** [comment]
@Kokiro  - See the [documentation](https://flask-authorize.readthedocs.io/en/latest/usage.html#jinja-support) for details on how to use the new Jinja support. I just did a patch update of this package and released it to PyPI. The version with Jinja support is `0.1.4`.

Let me know if you have any questions or feedback, thanks!
