### ISSUE TITLE
ImportError: cannot import name 'GroupRestrictionsMixin'

### ISSUE THREAD

**Issue by Kokiro** [bprinty/Flask-Authorize#24]
Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    from models import User
  File "/xyzy/models.py", line 3, in <module>
    from flask_authorize import GroupRestrictionsMixin, RoleRestrictionsMixin
ImportError: cannot import name 'GroupRestrictionsMixin'

**Comment by bprinty** [comment]
Another good catch - this one is an artifact of the documentation being out-of-date. I just updated the documentation [here](https://flask-authorize.readthedocs.io/en/latest/). Basically, there aren't separate mixins for group restrictions or role restrictions. For both types, just use the `RestrictionsMixin`:

```
    from flask_authorize import RestrictionsMixin

    class Group(db.Model, RestrictionsMixin):
        id = db.Column(db.Integer, primary_key=True)
        name = db.Column(db.String(255), nullable=False, unique=True)
```

You won't need to update your version of the package - this was just a documentation issue.

Thanks!
