### ISSUE TITLE
RestrictionMixin does not work as expected

### ISSUE THREAD

**Issue by Rmordente** [bprinty/Flask-Authorize#37]
When `_restrictions_` property model is set, there is no default value recorded in the database field that corresponds to the values specified in the class that inherits **RestricionMixin**. For example in the docs you can see something like: 

`class Group(db.Model, RestrictionMixin): 
    __restrictions__ = {
      'articles': ['update', 'delete']
    }`

I have seen that the **default_restrictions** function is not executed. Has anyone tested this functionality?

**Comment by bprinty** [comment]
Can you provide some code that reproduces what you're seeing? That will help me troubleshoot the issue.

**Comment by bprinty** [comment]
Closing because no response. Assuming it was solved by user.
