### ISSUE TITLE
Using authorize.has_role(‘<role>’) as decorator did not raised Unauthorized exception

### ISSUE THREAD

**Issue by julot** [bprinty/Flask-Authorize#40]
Unauthorize exception is never raised even though the user didn't have admin role if I use authorize.has_role as decorator like this (documentation says Unauthorize exception should be raised):

```python
@login_required
@authorize.has_role('admin')
def view():
    pass
```

But, Unauthorize exception is raised properly if user didn't have admin role if I use explicitly like this:

```python
@login_required
def view():
    if not authorize.has_role('admin'):
        raise Unauthorized
    pass
```

I use Flask-Login and only need a role-based control, so I don't set ACL nor group.

This is my model:

```python
class Role(db.Model, AllowancesMixin):
    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False, unique=True)

UserRole = db.Table(
    'user_role', db.Model.metadata,
    db.Column('user_id', db.Integer, db.ForeignKey('users.id')),
    db.Column('role_id', db.Integer, db.ForeignKey('roles.id'))
)

class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False, unique=True)
    password = db.Column(asuka.db.String, nullable=False)

    roles = db.relationship('Role', secondary=UserRole)

    def get_id(self):
        return self.name
```

**Comment by bprinty** [comment]
I can't seem to reproduce the issue with the current version (there are also pytests for that feature). Maybe it has something to do with the `Flask-Login` integration? Have you set the `user_loader` for Flask-Login? Something like:

```python
@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).first()
```

I'd also recommend returning `self.id` for the `User.get_id`  method instead of `self.name`.

**Comment by julot** [comment]
Yes, I already set `user_loader`.

I change `User.get_id` and `user_loader` as you suggested:

```python
class User(db.Model):
    def get_id(self):
        return self.id

@login_manager.user_loader
def load_user(user_id):
    flask.g.user = (
        models
        .User
        .query
        .filter(models.User.id == user_id)
        .options(sqlalchemy.orm.joinedload(models.User.roles))
        .first()
    )
    return flask.g.user
```

But the problem persists.

Well, it seems there's some complication down the road somewhere in my system.
For now I'll use the explicit method.
Thank you for your help.
