### ISSUE TITLE
Usage with factory pattern

### ISSUE THREAD

**Issue by d3s555** [bprinty/Flask-Authorize#41]
Hi,

Maybe before I being its nice to mention that I am new to flask and python, this is my first issue ever, so I am definitely a noob, feedback is welcome.

I am just opening this issue to ask about support of the factory pattern: https://flask.palletsprojects.com/en/1.1.x/patterns/appfactories/

I am using this template https://github.com/cookiecutter-flask/cookiecutter-flask and trying to integrate this package into it. 

In `extensions.py` I have added
```
from flask_authorize import Authorize
authorize = Authorize(None)
```
`view.py`
```
from app_name.extensions import authorize
```
`app.py`
```
from contentclub.extensions import authorize
authorize.Authorize(app)
```
I followed this patter because it was what they did for other items similar to this, e.g. sqlalchemy, flask_login etc. 

But I am getting :( `RuntimeError: Working outside of application context.` 

I know what it means generally speaking but in this case I am not sure what it is exactly or how I can fix it. It is my hypothesis that the `Authorize(None)` in `extensions.py` is actually going through initialising the None when there actually is not an app yet passed. So I have tried going with `authorize = None` but then I got `AttributeError: 'NoneType' object has no attribute 'has_role'` in the view, so I think the view is trying to access that object before app.py got done. Also  All of this might (is probably) completely wrong though so pointers would be appreciated.

P.S. I have done my best to check the docs thoroughly, I would suggest if a solution for this is present there it is highlighted and if not added. Unless its something started that everyone else would know how to do.

Thank you very much!

**Comment by bprinty** [comment]
When using the factory pattern for initializing the plugin, instantiate the `Authorize` class with no arguments:

```python
# in extensions.py file
from flask_authorize import Authorize
authorize = Authorize()
```

And then when registering the app with your extensions, use `init_app`:
```python
# in register_extensions function
authorize.init_app(app, db)
```

**Comment by bprinty** [comment]
I was able to get that cookiecutter project up and running with authorize. Here are the changes I made:

```python
# extensions.py
from flask_authorize import Authorize
authorize = Authorize() # <-- initialize it here
```

```python
# app.py
def register_extensions(app):
    """Register Flask extensions."""
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    csrf_protect.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    flask_static_digest.init_app(app)
    authorize.init_app(app, db) # <-- register it here
    return None
```
