### ISSUE TITLE
Owner ID always null in DB

### ISSUE THREAD

**Issue by msdcanderson** [bprinty/Flask-Authorize#42]
I am following the documentation.  Despite being logged in, I print the user ID to the console, before saving the record in the DB the owner ID is always stored as null.

![image](https://user-images.githubusercontent.com/20575321/86386375-9126c500-bc89-11ea-9c6c-609c43a69ce9.png)

I have copied and pasted the user code from the [documentation](https://flask-authorize.readthedocs.io/en/latest/usage.html#a-relevant-use-case).  I am using the latest version of flask-authorize.

I created a simple app and stored the code on [github](https://github.com/msdcanderson/example_flask_authorize) if it helps to look there.

My 'store' resource is:

```python
class NewStore(Resource):
    @classmethod
    @login_required
    @authorize.create(StoreModel)    
    def post(cls):
        store_json = request.get_json()
        store = store_schema.load(store_json)

        print(current_user.id)

        store.save_to_db()
        return {"message": gettext("STORE_CREATED")}, 201
```

The 'store' model is:

```python
from datetime import datetime
from typing import List
from flask_authorize import PermissionsMixin

from db import db


class StoreModel(db.Model, PermissionsMixin):
    __tablename__ = "stores"
    __permissions__ = dict(
        owner=['create','read', 'update', 'delete', 'revoke'],
        group=['read', 'update'],
        other=['read']
    )

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    description = db.Column(db.String(255))
    created_on = db.Column(db.DateTime, server_default=db.func.now())
    updated_on = db.Column(db.DateTime, onupdate=datetime.now())


    @classmethod
    def find_by_id(cls, _id: int) -> "StoreModel":
        return cls.query.filter_by(id=_id).first()

    @classmethod
    def find_all(cls) -> List["StoreModel"]:
        return cls.query.all()

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()
```

I plan eventually on expanding this to test the various possible ways of using flask-authorize.

Thanks for your help, it looks like a great plugin....if I can get it to work! :-)

**Comment by msdcanderson** [comment]
Do I need to add owner ID and group ID manually - is this missing from the documentation, or should flask-authorize be picking this up?

**Comment by bprinty** [comment]
Sorry for the delay! Yes, you need to manually associate owners and groups with restricted content. The documentation isn't clear on this; I'll add some text and examples showcasing how to do that.

**Comment by bprinty** [comment]
Thanks for the feedback!

**Comment by msdcanderson** [comment]
@bprinty thanks for confirming
