### ISSUE TITLE
Unable to add a second user_id relationship

### ISSUE THREAD

**Issue by tordne** [bprinty/Flask-Authorize#46]
Hi,

I've tried to use both your packages flask-authorize and flask-continuum. I abandoned flask_continuum, because apparently even the maintainer of continuum abandoned it himself.
So to version control my tables I started to use the SQLAlchemy idea of version history [SQLAlchemy version history](https://docs.sqlalchemy.org/en/13/_modules/examples/versioned_history/history_meta.html)
The only issue is that they don't add a user_id

I found other projects which used this version history, but they added their own "created_by_user" ForeignKey

On other tables where I didn't use any permission mixins, it works fine and I can add 2 user IDs with adding them using *foreign_keys=[user_id]
i.e.
`user_id = db.Column(UUID(as_uuid=True), db.ForeignKey("users.id"))`
`user = db.relationship("User", uselist=False, backref="users", foreign_keys=[user_id])`
`edit_user_id = db.Column(UUID(as_uuid=True), db.ForeignKey("users.id"))`
`edit_user = db.relationship("User", foreign_keys=[edit_user_id])`

On tables I did use the permissions mixins, it will give the following error
> qlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship App.owner - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.

I'm not sure how to solve this as I haven't really gone through your code, perhaps you have an idea?

**Comment by tordne** [comment]
Hi Blake,

What I've tried is change the line 378 in the mixins.py to the following
`        return relationship('User', foreign_keys=[cls.owner_id])`

I've also changed all the UUID's back to db.Integer

All the tests pass, but for some reason it still doesn't recognise it,

a pdb traceback shows the creation of tables:

> piro        | (Pdb) l
piro        |  17  	@cli.command("create_db")
piro        |  18  	def create_db():
piro        |  19  	    import pdb; pdb.set_trace()
piro        |  20  	    db.reflect()
piro        |  21  	    db.drop_all()
piro        |  22  ->	    db.create_all()
piro        |  23  	    db.session.commit()
piro        |  24  	
piro        |  25  	
piro        |  26  	@cli.command("seed_db")
piro        |  27  	def seed_db():
piro        | (Pdb) n
piro        | 2021-01-01 19:09:06,198 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
piro        | 2021-01-01 19:09:06,199 INFO sqlalchemy.engine.base.Engine {'name': 'user_group'}
piro        | 2021-01-01 19:09:06,201 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
piro        | 2021-01-01 19:09:06,201 INFO sqlalchemy.engine.base.Engine {'name': 'user_role'}
piro        | 2021-01-01 19:09:06,203 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
piro        | 2021-01-01 19:09:06,203 INFO sqlalchemy.engine.base.Engine {'name': 'user_to_profile'}
piro        | 2021-01-01 19:09:06,205 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
piro        | 2021-01-01 19:09:06,205 INFO sqlalchemy.engine.base.Engine {'name': 'groups'}
piro        | 2021-01-01 19:09:06,208 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
piro        | 2021-01-01 19:09:06,208 INFO sqlalchemy.engine.base.Engine {'name': 'groups_history'}
piro        | 2021-01-01 19:09:06,210 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
piro        | 2021-01-01 19:09:06,210 INFO sqlalchemy.engine.base.Engine {'name': 'roles'}
piro        | 2021-01-01 19:09:06,212 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
piro        | 2021-01-01 19:09:06,212 INFO sqlalchemy.engine.base.Engine {'name': 'roles_history'}
piro        | 2021-01-01 19:09:06,214 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
piro        | 2021-01-01 19:09:06,214 INFO sqlalchemy.engine.base.Engine {'name': 'users'}
piro        | 2021-01-01 19:09:06,215 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
piro        | 2021-01-01 19:09:06,216 INFO sqlalchemy.engine.base.Engine {'name': 'personal_details'}
piro        | 2021-01-01 19:09:06,217 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
piro        | 2021-01-01 19:09:06,217 INFO sqlalchemy.engine.base.Engine {'name': 'personal_details_history'}
piro        | 2021-01-01 19:09:06,219 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
piro        | 2021-01-01 19:09:06,219 INFO sqlalchemy.engine.base.Engine {'name': 'apps'}
piro        | 2021-01-01 19:09:06,224 INFO sqlalchemy.engine.base.Engine 
piro        | CREATE TABLE groups_history (
piro        | 	id INTEGER NOT NULL, 
piro        | 	name VARCHAR(255) NOT NULL, 
piro        | 	created_at TIMESTAMP WITHOUT TIME ZONE, 
piro        | 	updated_at TIMESTAMP WITHOUT TIME ZONE, 
piro        | 	edit_user_id INTEGER, 
piro        | 	restrictions TEXT, 
piro        | 	version INTEGER NOT NULL, 
piro        | 	changed TIMESTAMP WITHOUT TIME ZONE, 
piro        | 	PRIMARY KEY (id, version)
piro        | )
piro        | 
piro        | 
piro        | 2021-01-01 19:09:06,224 INFO sqlalchemy.engine.base.Engine {}
piro        | 2021-01-01 19:09:06,237 INFO sqlalchemy.engine.base.Engine COMMIT
piro        | 2021-01-01 19:09:06,241 INFO sqlalchemy.engine.base.Engine 
piro        | CREATE TABLE roles_history (
piro        | 	id INTEGER NOT NULL, 
piro        | 	name VARCHAR(255) NOT NULL, 
piro        | 	created_at TIMESTAMP WITHOUT TIME ZONE, 
piro        | 	updated_at TIMESTAMP WITHOUT TIME ZONE, 
piro        | 	edit_user_id INTEGER, 
piro        | 	allowances TEXT, 
piro        | 	version INTEGER NOT NULL, 
piro        | 	changed TIMESTAMP WITHOUT TIME ZONE, 
piro        | 	PRIMARY KEY (id, version)
piro        | )
piro        | 
piro        | 
piro        | 2021-01-01 19:09:06,241 INFO sqlalchemy.engine.base.Engine {}
piro        | 2021-01-01 19:09:06,245 INFO sqlalchemy.engine.base.Engine COMMIT
piro        | 2021-01-01 19:09:06,257 INFO sqlalchemy.engine.base.Engine 
piro        | CREATE TABLE users (
piro        | 	id SERIAL NOT NULL, 
piro        | 	email VARCHAR(250) NOT NULL, 
piro        | 	_password BYTEA NOT NULL, 
piro        | 	authenticated BOOLEAN, 
piro        | 	active BOOLEAN NOT NULL, 
piro        | 	email_confirmation_sent_on TIMESTAMP WITHOUT TIME ZONE, 
piro        | 	email_confirmed BOOLEAN, 
piro        | 	email_confirmed_on TIMESTAMP WITHOUT TIME ZONE, 
piro        | 	registered_on TIMESTAMP WITHOUT TIME ZONE, 
piro        | 	last_logged_in TIMESTAMP WITHOUT TIME ZONE, 
piro        | 	created_at TIMESTAMP WITHOUT TIME ZONE, 
piro        | 	updated_at TIMESTAMP WITHOUT TIME ZONE, 
piro        | 	PRIMARY KEY (id), 
piro        | 	UNIQUE (email)
piro        | )
piro        | 
piro        | 
piro        | 2021-01-01 19:09:06,257 INFO sqlalchemy.engine.base.Engine {}
piro        | 2021-01-01 19:09:06,264 INFO sqlalchemy.engine.base.Engine COMMIT
piro        | 2021-01-01 19:09:06,268 INFO sqlalchemy.engine.base.Engine 
piro        | CREATE TABLE personal_details_history (
piro        | 	id UUID NOT NULL, 
piro        | 	first_name VARCHAR(25), 
piro        | 	middle_name VARCHAR(25), 
piro        | 	surname VARCHAR(25), 
piro        | 	date_of_birth DATE, 
piro        | 	user_id INTEGER, 
piro        | 	edit_user_id INTEGER, 
piro        | 	version INTEGER NOT NULL, 
piro        | 	changed TIMESTAMP WITHOUT TIME ZONE, 
piro        | 	PRIMARY KEY (id, version)
piro        | )
piro        | 
piro        | 
piro        | 2021-01-01 19:09:06,268 INFO sqlalchemy.engine.base.Engine {}
piro        | 2021-01-01 19:09:06,271 INFO sqlalchemy.engine.base.Engine COMMIT
piro        | 2021-01-01 19:09:06,280 INFO sqlalchemy.engine.base.Engine 
piro        | CREATE TABLE groups (
piro        | 	id SERIAL NOT NULL, 
piro        | 	name VARCHAR(255) NOT NULL, 
piro        | 	created_at TIMESTAMP WITHOUT TIME ZONE, 
piro        | 	updated_at TIMESTAMP WITHOUT TIME ZONE, 
piro        | 	edit_user_id INTEGER, 
piro        | 	restrictions TEXT, 
piro        | 	version INTEGER NOT NULL, 
piro        | 	PRIMARY KEY (id), 
piro        | 	UNIQUE (name), 
piro        | 	FOREIGN KEY(edit_user_id) REFERENCES users (id)
piro        | )
piro        | 
piro        | 
piro        | 2021-01-01 19:09:06,280 INFO sqlalchemy.engine.base.Engine {}
piro        | 2021-01-01 19:09:06,286 INFO sqlalchemy.engine.base.Engine COMMIT
piro        | 2021-01-01 19:09:06,289 INFO sqlalchemy.engine.base.Engine 
piro        | CREATE TABLE roles (
piro        | 	id SERIAL NOT NULL, 
piro        | 	name VARCHAR(255) NOT NULL, 
piro        | 	created_at TIMESTAMP WITHOUT TIME ZONE, 
piro        | 	updated_at TIMESTAMP WITHOUT TIME ZONE, 
piro        | 	edit_user_id INTEGER, 
piro        | 	allowances TEXT, 
piro        | 	version INTEGER NOT NULL, 
piro        | 	PRIMARY KEY (id), 
piro        | 	UNIQUE (name), 
piro        | 	FOREIGN KEY(edit_user_id) REFERENCES users (id)
piro        | )
piro        | 
piro        | 
piro        | 2021-01-01 19:09:06,289 INFO sqlalchemy.engine.base.Engine {}
piro        | 2021-01-01 19:09:06,295 INFO sqlalchemy.engine.base.Engine COMMIT
piro        | 2021-01-01 19:09:06,303 INFO sqlalchemy.engine.base.Engine 
piro        | CREATE TABLE personal_details (
piro        | 	id UUID NOT NULL, 
piro        | 	first_name VARCHAR(25), 
piro        | 	middle_name VARCHAR(25), 
piro        | 	surname VARCHAR(25), 
piro        | 	date_of_birth DATE, 
piro        | 	user_id INTEGER, 
piro        | 	edit_user_id INTEGER, 
piro        | 	version INTEGER NOT NULL, 
piro        | 	PRIMARY KEY (id), 
piro        | 	FOREIGN KEY(user_id) REFERENCES users (id), 
piro        | 	FOREIGN KEY(edit_user_id) REFERENCES users (id)
piro        | )
piro        | 
piro        | 
piro        | 2021-01-01 19:09:06,303 INFO sqlalchemy.engine.base.Engine {}
piro        | 2021-01-01 19:09:06,306 INFO sqlalchemy.engine.base.Engine COMMIT
piro        | 2021-01-01 19:09:06,309 INFO sqlalchemy.engine.base.Engine 
piro        | CREATE TABLE user_group (
piro        | 	user_id INTEGER, 
piro        | 	group_id INTEGER, 
piro        | 	FOREIGN KEY(user_id) REFERENCES users (id), 
piro        | 	FOREIGN KEY(group_id) REFERENCES groups (id)
piro        | )
piro        | 
piro        | 
piro        | 2021-01-01 19:09:06,309 INFO sqlalchemy.engine.base.Engine {}
piro        | 2021-01-01 19:09:06,311 INFO sqlalchemy.engine.base.Engine COMMIT
piro        | 2021-01-01 19:09:06,317 INFO sqlalchemy.engine.base.Engine 
piro        | CREATE TABLE user_role (
piro        | 	user_id INTEGER, 
piro        | 	role_id INTEGER, 
piro        | 	FOREIGN KEY(user_id) REFERENCES users (id), 
piro        | 	FOREIGN KEY(role_id) REFERENCES roles (id)
piro        | )
piro        | 
piro        | 
piro        | 2021-01-01 19:09:06,318 INFO sqlalchemy.engine.base.Engine {}
piro        | 2021-01-01 19:09:06,319 INFO sqlalchemy.engine.base.Engine COMMIT
piro        | 2021-01-01 19:09:06,322 INFO sqlalchemy.engine.base.Engine 
piro        | CREATE TABLE user_to_profile (
piro        | 	user_id INTEGER, 
piro        | 	profile_id UUID, 
piro        | 	FOREIGN KEY(user_id) REFERENCES users (id), 
piro        | 	FOREIGN KEY(profile_id) REFERENCES personal_details (id)
piro        | )
piro        | 
piro        | 
piro        | 2021-01-01 19:09:06,322 INFO sqlalchemy.engine.base.Engine {}
piro        | 2021-01-01 19:09:06,324 INFO sqlalchemy.engine.base.Engine COMMIT
piro        | 2021-01-01 19:09:06,334 INFO sqlalchemy.engine.base.Engine 
piro        | CREATE TABLE apps (
piro        | 	id UUID NOT NULL, 
piro        | 	name VARCHAR(255) NOT NULL, 
piro        | 	h_ref VARCHAR(70) NOT NULL, 
piro        | 	icon VARCHAR(70) NOT NULL, 
piro        | 	version INTEGER NOT NULL, 
piro        | 	updated_at TIMESTAMP WITHOUT TIME ZONE, 
piro        | 	edit_user_id INTEGER, 
piro        | 	other_permissions TEXT, 
piro        | 	owner_id INTEGER, 
piro        | 	owner_permissions TEXT, 
piro        | 	group_id INTEGER, 
piro        | 	group_permissions TEXT, 
piro        | 	PRIMARY KEY (id), 
piro        | 	FOREIGN KEY(edit_user_id) REFERENCES users (id), 
piro        | 	FOREIGN KEY(owner_id) REFERENCES users (id), 
piro        | 	FOREIGN KEY(group_id) REFERENCES groups (id)
piro        | )
piro        | 
piro        | 
piro        | 2021-01-01 19:09:06,334 INFO sqlalchemy.engine.base.Engine {}
piro        | 2021-01-01 19:09:06,339 INFO sqlalchemy.engine.base.Engine COMMIT
piro        | 2021-01-01 19:09:06,340 INFO sqlalchemy.engine.base.Engine CREATE INDEX ix_apps_name ON apps (name)
piro        | 2021-01-01 19:09:06,341 INFO sqlalchemy.engine.base.Engine {}
piro        | 2021-01-01 19:09:06,342 INFO sqlalchemy.engine.base.Engine COMMIT
piro        | 2021-01-01 19:09:06,348 INFO sqlalchemy.engine.base.Engine CREATE INDEX ix_apps_edit_user_id ON apps (edit_user_id)
piro        | 2021-01-01 19:09:06,349 INFO sqlalchemy.engine.base.Engine {}
piro        | 2021-01-01 19:09:06,350 INFO sqlalchemy.engine.base.Engine COMMIT


But the it still gives the following errors:

> piro        | 2021-01-01 19:11:53,589 INFO sqlalchemy.engine.base.Engine COMMIT
piro        | Traceback (most recent call last):
piro        |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2635, in _determine_joins
piro        |     self.primaryjoin = join_condition(
piro        |   File "<string>", line 2, in join_condition
piro        |   File "<string>", line 2, in _join_condition
piro        |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
piro        |     return fn(*args, **kwargs)
piro        |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/selectable.py", line 964, in _join_condition
piro        |     cls._joincond_trim_constraints(
piro        |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/selectable.py", line 1077, in _joincond_trim_constraints
piro        |     raise exc.AmbiguousForeignKeysError(
piro        | sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'apps' and 'users'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.
piro        | 
piro        | The above exception was the direct cause of the following exception:
piro        | 
piro        | Traceback (most recent call last):
piro        |   File "/home/flask/app/web/manage.py", line 59, in <module>
piro        |     cli()
piro        |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
piro        |     return self.main(*args, **kwargs)
piro        |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 586, in main
piro        |     return super(FlaskGroup, self).main(*args, **kwargs)
piro        |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
piro        |     rv = self.invoke(ctx)
piro        |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
piro        |     return _process_result(sub_ctx.command.invoke(sub_ctx))
piro        |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
piro        |     return ctx.invoke(self.callback, **ctx.params)
piro        |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
piro        |     return callback(*args, **kwargs)
piro        |   File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
piro        |     return f(get_current_context(), *args, **kwargs)
piro        |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 426, in decorator
piro        |     return __ctx.invoke(f, *args, **kwargs)
piro        |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
piro        |     return callback(*args, **kwargs)
piro        |   File "/home/flask/app/web/manage.py", line 33, in seed_db
piro        |     u = User(email=user["email"], plaintext_password=user["password"])
piro        |   File "<string>", line 2, in __init__
piro        |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/instrumentation.py", line 388, in _new_state_if_none
piro        |     state = self._state_constructor(instance, self)
piro        |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 884, in __get__
piro        |     obj.__dict__[self.__name__] = result = self.fget(obj)
piro        |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/instrumentation.py", line 214, in _state_constructor
piro        |     self.dispatch.first_init(self, self.class_)
piro        |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
piro        |     fn(*args, **kw)
piro        |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3411, in _event_on_first_init
piro        |     configure_mappers()
piro        |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3299, in configure_mappers
piro        |     mapper._post_configure_properties()
piro        |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1965, in _post_configure_properties
piro        |     prop.init()
piro        |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/interfaces.py", line 197, in init
piro        |     self.do_init()
piro        |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2077, in do_init
piro        |     self._setup_join_conditions()
piro        |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2141, in _setup_join_conditions
piro        |     self._join_condition = jc = JoinCondition(
piro        |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2524, in __init__
piro        |     self._determine_joins()
piro        |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2687, in _determine_joins
piro        |     util.raise_(
piro        |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
piro        |     raise exception
piro        | sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship App.owner - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.

I'm not that proficient writing all the pytests and had quite a lot of problems looking into your code.

Do you have any idea of what might be going wrong?

**Comment by bprinty** [comment]
Hi @tordne, thanks for reaching out! I haven't tested this package with a model defining multiple foreign key references to the same external table. Could be something related to the way I'm defining foreign keys in the various Mixins provided with this package. I'll do some testing locally to see if I can re-create the issue and if so, will work on a fix.

I'll keep you updated on what I find. In the meantime, if you could post a minimal working example of an application highlighting the conditions that created this bug, I can use it for testing my fix. Thanks!
