### ISSUE TITLE
Need to be able to specify the names of specific tables

### ISSUE THREAD

**Issue by amthorn** [bprinty/Flask-Authorize#49]
Right now the tables *must* be named "users" and the classes must be named "Group". In our application, we don't follow this standard, we use "GroupModel" to specify classes and we go with singular table names: e.g. "user". I don't want to have to migrate tables.

Thus, i propose to add decorators to be able to set the SQLAlchemy classes that should be used, rather than hardcoding the strings for the tables/class names into the plugin. Once the decorator is used, it can refer to the __tablename__ attribute on the class to get the table name. One decorator should exist for groups, users, and roles. If not provided, default to something sane.

**Comment by amthorn** [comment]
submitted a PR for this: https://github.com/bprinty/Flask-Authorize/pull/50

**Comment by bprinty** [comment]
You make a great point - allowing this type of customization would definitely be useful. Thanks for the PR! I'm looking through it now and will let you know when it gets merged into the main branch. I'll likely create a new release including the fix.

**Comment by bprinty** [comment]
I haven't yet added documentation for using this feature (it should definitely be included so people can use it). A new release (`0.2.3`) was just pushed to PyPi with these additions.
