### ISSUE TITLE
type object 'Model' has no attribute '_decl_class_registry'

### ISSUE THREAD

**Issue by janash** [bprinty/Flask-Authorize#53]
I'm having an issue with the `PermissionsMixin` model when `sqlalchemy` is upgraded to version 1.4.x (1.3 works fine).  To get this error, install `flask-authorize` in an environment with sqlalchemy > 1.3 and run pytest. You will see

```
flask_authorize/mixins.py:196: in default_restrictions
    gather_models()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def gather_models():
        """
        Inspect sqlalchemy models from current context and set global
        dictionary to be used in url conversion.
        """
        global MODELS

        from flask import current_app
        if 'sqlalchemy' not in current_app.extensions:
            return
        check = current_app.config['AUTHORIZE_IGNORE_PROPERTY']

        # inspect current models and add to map
        db = current_app.extensions['sqlalchemy'].db
>       for cls in db.Model._decl_class_registry.values():
E       sqlalchemy.exc.StatementError: (builtins.AttributeError) type object 'Model' has no attribute '_decl_class_registry'
E       [SQL: INSERT INTO groups (id, name, "desc", restrictions) VALUES (?, ?, ?, ?)]
E       [parameters: [{'name': 'readers', 'id': 100, 'desc': None}]]

flask_authorize/mixins.py:101: StatementError
```

Notably - `type object 'Model' has no attribute '_decl_class_registry'`

Here's a direct link to the line

https://github.com/bprinty/Flask-Authorize/blob/5f55e21a4623fd787c07b4783ad2b643a036d37a/flask_authorize/mixins.py#L101

There must have been a change to sqlalchemy models, but I haven't figured it out yet.

**Comment by bprinty** [comment]
Thanks for the heads up! This is a tricky one - looks like the declarative system in 1.3 was changed. I'll likely need to figure out a different way of dynamically gathering classes for permissions checks. Looking into it now, and in the meantime I can add a version limit to the requirements file for the project.

**Comment by bprinty** [comment]
@janash - I just fixed the issue and pushed an updated version (`0.2.6`) to PyPi. Thanks for filing the ticket!

**Comment by bprinty** [comment]
Let me know if you run into any issues locally. Tested with SQLAlchemy `1.4.2`.

**Comment by bprinty** [comment]
Also, FYI - I just changed the name of the default branch to `main` instead of `master` to match other open-source projects. You can update your local copy by re-cloning or running the following:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
