### ISSUE TITLE
Flask-SQLAlchemy Dependency needed?

### ISSUE THREAD

**Issue by mmarihart** [bprinty/Flask-Authorize#56]
Hi, title more or less already states my question.

More details:
I refactored my flask application to use the SQLAlchemy package instead of Flask-SQLAlchemy, due to certain requirements.
After removing Flask-SQLAlchemy manually, everything regarding the authorization functionality still seems to work and my tests finish successfully.

I am not using all the features of Flask-Authorize though. Therefore, the question if Flask-SQLAlchemy is still required came up?

Thanks.

**Comment by bprinty** [comment]
Flask-Authorize depends on the Flask-SQLAlchemy plugin being registered to the application when it dynamically gathers Model metadata for Allowances and Restrictions. For content authorization, it looks like you might be able to use it without requiring Flask-SQLAlchemy. That said, I haven't fully tested out the plugin without the Flask-SQLAlchemy requirement.

This project probably doesn't *need* to depend on Flask-SQLAlchemy, but it would take significant effort to restructure it. If you and others keep running into this issue, we might be able to accommodate the restructuring in a future release.
