### ISSUE TITLE
Default allowance are failing

### ISSUE THREAD

**Issue by quiche-sama** [bprinty/Flask-Authorize#65]
Hey there, 

I think the piece of code : 
```python
    role = RoleFactory.create(
        name='unallowed',
        allowances=default_allowances()
    )
```
do not work because of the default_allowance method, and is causing quite fails in the unit tests.
It seems that, in that method , especially in the 
```python
mixins.py
def gather_models():
...
    db = current_app.extensions['sqlalchemy'].db
...
```
It seems to be failing, as db attribute seems not to exist. 

Hope i'm not missing something, i'm trying a bit to have a look, though not super super good in sqlalchemy here. 
I suppose the way the code is trying to fetch all the models to define default allowances needs to be changed

Cheers

**Comment by tordne** [comment]
Hi Quiche,

I had an old app using this package, running on python 3.9 container and it worked, I just tried to update things and I got the same error as you said  here is a list of my dev-requirements.txt 

#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile dev-requirements.in
#
alabaster==0.7.12         # via sphinx
appdirs==1.4.4            # via black
attrs==20.3.0             # via -c requirements.txt, pytest
babel==2.9.0              # via sphinx
black==20.8b1             # via -r dev-requirements.in
certifi==2020.12.5        # via requests
chardet==4.0.0            # via requests
click==7.1.2              # via -c requirements.txt, black
coverage==5.4             # via -r dev-requirements.in, pytest-cov
docutils==0.16            # via sphinx
flake8==3.8.4             # via -r dev-requirements.in
idna==2.10                # via -c requirements.txt, requests
imagesize==1.2.0          # via sphinx
iniconfig==1.1.1          # via pytest
isort==5.7.0              # via -r dev-requirements.in
jinja2==2.11.3            # via -c requirements.txt, sphinx
markupsafe==1.1.1         # via -c requirements.txt, jinja2
mccabe==0.6.1             # via flake8
mypy-extensions==0.4.3    # via black
packaging==20.9           # via pytest, sphinx
pathspec==0.8.1           # via black
pluggy==0.13.1            # via pytest
py==1.10.0                # via pytest
pycodestyle==2.6.0        # via flake8
pyflakes==2.2.0           # via flake8
pygments==2.7.4           # via sphinx
pyparsing==2.4.7          # via packaging
pytest-cov==2.11.1        # via -r dev-requirements.in
pytest==6.2.2             # via -r dev-requirements.in, pytest-cov
pytz==2021.1              # via -c requirements.txt, babel
regex==2020.11.13         # via black
requests==2.25.1          # via sphinx
sadisplay==0.4.9          # via sphinxcontrib.sadisplay
six==1.15.0               # via -c requirements.txt, sphinxcontrib-httpdomain
snowballstemmer==2.1.0    # via sphinx
sphinx==3.4.3             # via -r dev-requirements.in, sphinxcontrib-httpdomain, sphinxcontrib.plantuml, sphinxcontrib.sadisplay
sphinxcontrib-applehelp==1.0.2  # via sphinx
sphinxcontrib-devhelp==1.0.2  # via sphinx
sphinxcontrib-htmlhelp==1.0.3  # via sphinx
sphinxcontrib-httpdomain==1.7.0  # via -r dev-requirements.in
sphinxcontrib-jsmath==1.0.1  # via sphinx
sphinxcontrib-qthelp==1.0.3  # via sphinx
sphinxcontrib-serializinghtml==1.1.4  # via sphinx
sphinxcontrib.plantuml==0.19  # via -r dev-requirements.in
sphinxcontrib.sadisplay==0.3.3.dev20180712  # via -r dev-requirements.in
sqlalchemy==1.3.23        # via -c requirements.txt, sadisplay
toml==0.10.2              # via black, pytest
typed-ast==1.4.2          # via black
typing-extensions==3.7.4.3  # via black
urllib3==1.26.3           # via requests

# The following packages are considered to be unsafe in a requirements file:
# setuptools

**Comment by quiche-sama** [comment]
Thx a lot mate 👍
