### ISSUE TITLE
Add python 3.10 3.11 3.12 for tests

### ISSUE THREAD

**Issue by quichef** [bprinty/Flask-Authorize#68]
Hey there, 

i'm happily using Flask Authorize and thought it could be an idea to update the pythoon versions used for the CI 😄 

Opened the PR accordingly, it also contains Actions version update https://github.com/bprinty/Flask-Authorize/pull/67

Hope its ok, and wish you a great end of the year period

**Comment by bprinty** [comment]
PR merged. Thank you!
