### ISSUE TITLE
Question on awesome

### ISSUE THREAD

**Issue by quichef** [bprinty/Flask-Authorize#70]
Hey there, 

Wanted to know if that would be ok to list Flask-Authorize in here : https://github.com/humiaozuzu/awesome-flask 
More or less the first result when i google awesome flask 😛 

Cheers

**Comment by quichef** [comment]
hey, checking up

**Comment by atcata** [comment]
Glad you find the project helpful! Feel free to submit a PR to add it to that list if you want.

**Comment by bprinty** [comment]
Glad you find the project helpful! Feel free to submit a PR to add it to that list if you want.
